### ISSUE TITLE
Trading in Binance with HA

### ISSUE THREAD

**Issue by NapalmCandy** [drinfernoo/homeassistant-binance#10]
Hi,

I see on the API restrictions options on Binance account, that it is possible to add/remove new trades from the API. So, I am want to do a bot on HA that can buy/sell. So, can you add these options?

Thanks

**Comment by drinfernoo** [comment]
Those options are available to the Binance API, but I'm not interested in implementing them here.

**Comment by NapalmCandy** [comment]
We are really interested to create a bot inside HA. We can pay you for your time... what is your price?

**Comment by drinfernoo** [comment]
I really don't have much time to spend on this project at the moment...

There are other packages that handle trading via the Binance API, and this one isn't even really working at the moment, so it would need a good amount of work to get it functional again before I even looked at adding new features.

**Comment by NapalmCandy** [comment]
I have working your integration on HA 🤷🏻‍♂️

I searched for other integrations, and only I found for Coinbase, but Coinbase has a lot higher fees than Binance.

But I understand you, you are working on other projects. Thank anyway 🤗

**Comment by drinfernoo** [comment]
One I'm familiar with is: https://github.com/CyberPunkMetalHead/Binance-News-Sentiment-Bot

It isn't an integration, but a separate Python package... I'm not sure that I think integrating it into HA would be very advantageous (or secure), considering there are simple implementations of such bots readily available.

**Comment by NapalmCandy** [comment]
I don't think HA it is very advantageous or secure, but it is the platform I know and where I created the bot. I don't want other bots, just want to use my own bot
