### ISSUE TITLE
Any way to know why not working

### ISSUE THREAD

**Issue by iNaiks** [drinfernoo/homeassistant-binance#11]
Hi, I've recently installed with hacs and appear in HACS->Integrations.

I added to my configuration.yalm this:

binance:
  name: MyBinance
  api_key: ***********
  api_secret: ************
  

I've Created an api key and secret on Binance (photo1)

![photo1](https://user-images.githubusercontent.com/72868890/140167574-7aef8a77-0ac2-4c06-9591-ead2ff364d5c.png)

But always shows this error on server log (photo2)
![photo2](https://user-images.githubusercontent.com/72868890/140167604-ed6602d9-360f-4ad4-9ed1-77cae072219f.png)

I tried 2 times with different APIs on different days. But nothing.
There is any debug log to see why there is this error?

**Comment by drinfernoo** [comment]
Have you set the domain correctly?

**Comment by iNaiks** [comment]
No, sorry i've not used the domain.
In my case is "com" ? (i have account on binance.com)

**Comment by iNaiks** [comment]
Yes worksss very thanks.

PD: Any way to see the total ammount in USD of my wallet?

**Comment by iNaiks** [comment]
Yes worksss very thanks.

PD: Any way to see the total ammount in USD of my wallet? (like on the top in the app in wallet section)

**Comment by drinfernoo** [comment]
I've got an issue open (#9) to implement that, but not at this time.
