### ISSUE TITLE
Issue with platform sensor

### ISSUE THREAD

**Issue by rousselnic** [drinfernoo/homeassistant-binance#5]
Hello,

I tried installing your binance integration but I still got the same error : 

Unable to prepare setup for platform binance.sensor: Platform not found (cannot import name 'SensorEntity' from 'homeassistant.components.sensor' (/volume1/@appstore/homeassistant/env/lib/python3.8/site-packages/homeassistant/components/sensor/__init__.py)).

I using it on synology with python3.8.

Do you have any ideas ?
Thanks

**Comment by drinfernoo** [comment]
That's... odd 🤔 I'm not sure why this would happen, as it installs and works fine for me. You're installing from HACS? What version of Home Assistant?

**Comment by rousselnic** [comment]
Yes I installed it from HACS, I think that autentication API work fine, but setup.py don't initialize sensor. 
The network flow looks good too, I see it go out to api.binance.com.
I tried too to install binance-python library but I've some errors during installation .

Version | 2021.1.5
Installation Type | Home Assistant Core
Development | false
Supervisor | false
Docker | false
Virtual Environment | true
Python Version | 3.8.8
Operating System Family | Linux
Operating System Version | 3.2.40
CPU Architecture | armv7l
Timezone | Europe/Paris

**Comment by drinfernoo** [comment]
It appears that `SensorEntity` didn't exist until 2021.4.0: https://github.com/home-assistant/core/commit/e0cd7072d6480ff314e4cf1935decc9a22d46a9e#diff-f864c7480678e548519b8ba7f8dd17d8dfd2518f04a231b6553f277d54bd110d

I'll update the HA version requirement on HACS, as when I made this I wasn't really aware of what the minimum version should be, but this seems to have solved that little issue.

To use this integration, you'll need HA 2021.4.0 or higher.

**Comment by rousselnic** [comment]
pity...
Many thanks for your fast answers !
